services:
  taildrop-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taildrop-app
    network_mode: "host"
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ~/Downloads/Taildrop:/app/received
    restart: unless-stopped
